### ISSUE TITLE
rst example can't be easily copied

### ISSUE THREAD

**Issue by kparal** [potch/unmaintained.tech#10]
As it is currently rendered at http://unmaintained.tech/ , the rst example can't be easily copied and pasted, because the indentation information is lost. After copy and paste, this is the output:
```
 .. image:: http://unmaintained.tech/badge.svg
:target: http://unmaintained.tech/
:alt: No Maintenance Intended 
```
while it should be:
```
.. image:: http://unmaintained.tech/badge.svg
  :target: http://unmaintained.tech/
  :alt: No Maintenance Intended 
```

**Comment by potch** [comment]
I have in fact fixed this just now!
