### ISSUE TITLE
Who owns the domain?

### ISSUE THREAD

**Issue by cdzombak** [potch/unmaintained.tech#4]
`.tech` domains are relatively expensive<sup>1</sup> to renew. Who owns `unmaintained.tech`, and can I donate to ensure it remains online so I can confidently link to it long-term from projects' `README`s?

<sup>1</sup>: NameCheap charges something in the $45-50/year range when it's not on sale.

**Comment by potch** [comment]
I own the domain. I'm personally invested in keeping this one going for the long haul, but will definitely ask around if the price gets annoying. I might put up a gofundme when the domain comes up, but no need to donate right now.

Thanks for your support!

**Comment by cdzombak** [comment]
@potch cool; thanks. I'll continue watching the repo, and if you want to ping me in the future my email's chris@chrisdzombak.net
