### ISSUE TITLE
The badge is confusing

### ISSUE THREAD

**Issue by felixfbecker** [potch/unmaintained.tech#7]
Status badges from shields.io follow a specific pattern. The left side contains a short item name, and the right side the status of that item. Another way to put it: The right side can change, the left side stays the same. That's why the right side can have different colors depending on the status. The badge should therefor rather be:

![badge](https://img.shields.io/badge/maintenance-not%20intented-red.svg?style=flat)

**Comment by potch** [comment]
I agree that it doesn't match the typical pattern, but in the in the matter of being clear and concise, the current version works just fine.
